# -*- coding: utf-8 -*-
"""Copy of lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZn56gn1Ffn86gG-dd0pinkDZ1PfJ6vJ

# Initialization, utilities (no TODOs)
"""

import torch
import torchvision
import torch.nn as nn
import argparse
import PIL
import random

from skimage.io import imread, imshow, imread_collection, concatenate_images
import matplotlib.pyplot as plt
from torchsummary import summary

def to_list(img):
    return list(map(int, img.view((28*28,)).tolist()))
    
SCALE_OFF = 0    
SCALE_RANGE = 1
SCALE_01 = 2
    

def show_image(tens, imgname=None, scale=SCALE_01):
    """
    Show an image contained in a tensor. The tensor will be reshaped properly, as long as it has the required 28*28 = 784 entries.
    
    If imgname is provided, the image will be saved to a file, otherwise it will be stored in a temporary file and displayed on screen.
    
    The parameter scale can be used to perform one of three scaling operations:
        SCALE_OFF: No scaling is performed, the data is expected to use values between 0 and 255
        SCALE_RANGE: The data will be rescaled from whichever scale it has to be between 0 and 255. This is useful for data in an unknown/arbitrary range. The lowest value present in the data will be 
        converted to 0, the highest to 255, and all intermediate values will be assigned using linear interpolation
        SCALE_01: The data will be rescaled from a range between 0 and 1 to the range between 0 and 255. This can be useful if you normalize your data into that range.
    """
    r = tens.max() - tens.min()
    img = PIL.Image.new("L", (28,28))
    scaled = tens
    if scale == SCALE_RANGE:
        scaled = (tens - tens.min())*255/r
    elif scale == SCALE_01:
        scaled = tens*255
    img.putdata(to_list(scaled))
    if imgname is None:
        img.show()
    else:
        img.save(imgname)

"""# Classification (5 TODOs)"""

# Used for both tasks
loss_fn = torch.nn.BCELoss()

# TODO 1: Choose a digit
digit = 8

# TODO 2: Change number of training iterations for classifier
n0 = 40



# TODO 3
# Change Network architecture of the discriminator/classifier network. It should have 784 inputs and 1 output (0 = fake, 1 = real)
class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator,self).__init__()
        #Define inputs, outputs
        self.linear1 = nn.Linear(784,512)
        self.linear2 = nn.Linear(512,256)
        self.linear3 = nn.Linear(256,128)
        self.linear4 = nn.Linear(128,1)
        self.relu1 = nn.LeakyReLU()
        self.relu2 = nn.LeakyReLU()
        self.relu3 = nn.LeakyReLU()
        self.sig1 = nn.Sigmoid()
        self.dropout = nn.Dropout(0.6)
        
    def forward(self, x):
        h = self.linear1(x)
        h = self.relu1(h)
        h = self.dropout(h)
        h = self.linear2(h)
        h = self.relu2(h)
        h = self.dropout(h)
        h = self.linear3(h)
        h = self.relu3(h)
        h = self.dropout(h)
        h = self.linear4(h)
        return self.sig1(h)

# TODO 4
# Implement training loop for the classifier:
# for i in range(n0):
#     zero gradients
#     calculate predictions for given x
#     calculate loss, comparing the predictions with the given y
#     calculate the gradient (loss.backward())
#     print i and the loss
#     perform an optimizer step
def train_classifier(opt, model, x, y):
    for i in range(n0):
      opt.zero_grad()
      y_pred = model(x)
      loss = loss_fn(y_pred, y)
      loss.backward()
      print(i,loss)
      opt.step()
    pass

# TODO 5
# Instantiate the network and the optimizer
# call train_classifier with the training set
# Calculate metrics on the validation set 
# Example: 
#      y_pred = net(x_validation[labels_validation == 3]) calculates all predictions for all images we know to be 3s
#      (y_pred > 0.5) is a tensor that tells you if a given image was classified as your chosen digit (True) or not (False)
#      You can convert this tensor to 0s and 1s by calling .float()
#      (y_pred > 0.5).sum() will tell you how many of these predictions were true
# You are supposed to calculate:
#     For each digit from 0 to 9, which number percentage of images that were of that digit were predicted as your chosen digit
#     The percentage of digits that were classified correctly (i.e. that were your digit and predicted as such, or were another digit and not predicted as your digit)
#     This last value (accuracy) should be over 90% (preferably over 98%; precision and recall may be lower than that, 90-93% would be decent values)
#     Precision (which percentage of images identified as your chosen digit was actually that digit: TP/(TP+FP))
#     Recall (which percentage of your chosen digit was identified as such: TP/(TP+FN))
def classify(x_train, y_train, x_validation, labels_validation):
    model = Discriminator()
    optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
    train_classifier(optimizer, model, x_train, y_train)
    tp = 0
    fn = 0
    fp = 0
    tn = 0
    myList = [0,0,0,0,0,0,0,0,0,0]
    for i in range(10):
      y_pred = model(x_validation[labels_validation == i])
      imageList = x_validation[labels_validation == i]
      if (i == digit):
        tp =  ((y_pred.float() > 0.5).sum()).item()
        print(y_pred.shape[0])
        fn = ((y_pred.float() < 0.5).sum()).item()
        myList[i] = fn
        worst=torch.argmin(y_pred.float()).item()
        show_image(imageList[worst], "FN%d.png"%(i), scale = SCALE_01)
      else:
        fp = fp + ((y_pred.float() > 0.5).sum()).item()
        worst=torch.argmax(y_pred.float()).item()
        show_image(imageList[worst], "FP%d.png"%(i), scale = SCALE_01)
        myList[i] = fp
        tn = tn + ((y_pred.float() < 0.5).sum()).item()
    print(myList)
    print("TP ",tp,"FN ",fn,"FP ",fp,"TN ",tn)
    print(tp,fn,fp,tn)
    print("Accuracy: " , (tp+tn)/(tp+tn+fn+fp))
    print("Precision: " , (tp/(tp+fp)))
    print("Recall: " , (tp/(tp+fn)))
    pass

"""# GAN (5 TODOs)"""

# TODO 6: Change number of total training iterations for GAN, for the discriminator and for the generator
n = 20
#Disc Train
n1 = 50
#gen Train
n2 = 50

# TODO 7
# Change Network architecture of the generator network. It should have 100 inputs (will be random numbers) and 784 outputs (one for each pixel, each between 0 and 1)
class Generator(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(100, 128)
        self.linear2 = nn.Linear(128, 256)
        self.linear3 = nn.Linear(256, 512)
        self.linear4 = nn.Linear(512, 784)
        self.dropout = nn.Dropout(0.6)
        self.relu1 = nn.LeakyReLU()
        self.relu2 = nn.LeakyReLU()
        self.relu3 = nn.LeakyReLU()
        self.sig = nn.Sigmoid()
        self.tanh = nn.Tanh()
    def forward(self, x):
        h = self.linear1(x)
        h = self.relu1(h)
        h = self.dropout(h)
        h = self.linear2(h)
        h = self.relu2(h)
        h = self.dropout(h)
        h = self.linear3(h)
        h = self.relu3(h)
        h = self.dropout(h)
        h = self.linear4(h)
       
        return self.sig(h)

# TODO 8
# Implement training loop for the discriminator, given real and fake data:
# for i in range(n1):
#     zero gradients
#     calculate predictions for the x known as real 
#     calculate loss, comparing the predictions with a tensor consisting of 1s (we want all of these samples to be classified as real)
#     calculate the gradient (loss_true.backward())
#     calculate predictions for the x known as fake
#     calculate loss, comparing the predictions with a tensor consisting of 0s (we want all of these samples to be classified as fake)
#     calculate the gradient (loss_false.backward())
#     print i and both of the loss values
#     perform an optimizer step
def train_discriminator(opt, discriminator, x_true, x_false):
  print("Training discriminator")
  for i in range(n1):
      opt.zero_grad()
      y_pred = discriminator(x_true)
      loss_true = loss_fn(y_pred,torch.ones_like(y_pred))
      loss_true.backward()
      
      y_pred_false = discriminator(x_false)
      loss_false = loss_fn(y_pred_false, torch.zeros_like(y_pred_false))
      loss_false.backward()
      print(i,"X_True: " ,loss_true,"X_false: ", loss_false)
      opt.step()

# TODO 9 
# Implement training loop for the generator:
# for i in range(n2):
#     zero gradients 
#     generate some random inputs
#     calculate generated images by passing these inputs to the generator
#     pass the generated images to the discriminator to predict if they are true or fake
#     calculate the loss, comparing the predictions with a tensor of 1s (the *generator* wants the discriminator to classify its images as real)
#     calculate the gradient (loss.backward())
#     print i and the loss
#     perform an optimization step
def train_generator(opt, generator, discriminator):
  print("Training generator")
  for i in range(n2):
    opt.zero_grad()
    noisy_images = torch.randn((100,100))
    gen_images = generator(noisy_images)
    
    y_pred = discriminator(gen_images)
    loss = loss_fn(y_pred, torch.ones_like(y_pred))
    loss.backward()
    print(i,loss)
    opt.step()

# TODO 10
# Implement GAN training loop:
# Generate some random images (with torch.rand) as an initial collection of fakes
# Instantiate the two networks and two optimizers (one for each network!)
# for i in range(n):
#    call train_discriminator with the given real images and the collection of fake images 
#    call train_generator 
#    generate some images with the current generator, and add a random selection of old fake images (e.g. 100 random old ones, and 100new ones = 200 in total)
#    this will be your new collection of fake images
#    save some of the current fake images to a file (use a filename like "sample_%d_%d.png"%(i,j) so you have some samples from each iteration so you can see if the network improves)
# If you read the todos above, your training code will print the loss in each iteration. The loss for the discriminator and the generator should decrease each time their respective training functions are called 
# The images should start to look like numbers after just a few (could be after 1 or 2 already, or 3-10) iterations of *this* loop
def gan(x_real):
    G = Generator()
    D = Discriminator()
    gen_optimizer = torch.optim.Adam(G.parameters(), lr = 0.0001)
    disc_optimizer = torch.optim.Adam(D.parameters(), lr = 0.0001)

    x_false = torch.rand((100,784))
    show_image(x_false[0], "NoiseIn.png", scale = SCALE_01)
    show_image(x_real[0], "RealIn.png", scale = SCALE_01)
    #print("X_real shape is :" , x_real[0].shape)
    
    for i in range(n):
      train_discriminator(disc_optimizer,D,x_real,x_false)
      train_generator(gen_optimizer,G,D)
      x_pred = G(torch.randn((100,100))).detach()
      idx = torch.randperm(x_false.size(0))
      select_idx = idx[:100]
      selected = x_false[select_idx,:]
      x_false = torch.cat((selected,x_pred))
      show_image(x_pred[0], "train_%d.png"%(i), scale = SCALE_01)

"""# Main (no TODOs)"""

def main(rungan):
    """
    You do not have to change this function!
    
    It will:
        automatically download the data set if it doesn't exist yet
        make sure all tensor shapes are correct
        normalize the images (all pixels between 0 and 1)
        provide labels for the classification task (0 for all images that are not your digit, 1 for the ones that are)
        extract the images of your chosen digit for the GAN
    """
    train = torchvision.datasets.MNIST(".", download=True)
    x_train = train.data.float().view(-1,28*28)/255.0
    print("x Train shape is:" , x_train.shape)
    labels_train = train.targets
    print("Label Train shape is:" , labels_train.shape)
    y_train = (labels_train == digit).float().view(-1,1)
    print("Y Train shape is:" , y_train.shape)
    
    validation = torchvision.datasets.MNIST(".", train=False)
    x_validation = validation.data.float().view(-1,28*28)/255.0
    print("x val shape is:" , x_validation.shape)
    labels_validation = validation.targets
    
    if rungan:
        gan(x_train[labels_train == digit])
    else:
        classify(x_train, y_train, x_validation, labels_validation)

"""# Test call (TODO: TEST)"""

# NOTE: This will not work until you have done TODO 1 above! 
# If you have not done TODO 1 yet, you will get: AttributeError: 'bool' object has no attribute 'float'
GAN = True
main(GAN)